name: publish

on:
  push:
    branches:
      - master
    tags: 
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic release number"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
      REGISTRY: ${{ needs.config-aws.outputs.registry }}
      AWS_REGION: ${{ needs.config-aws.outputs.region }}
      INVOKE_DEPLOY: ${{ github.event.inputs.invokeDeploy || 'false' }}
    steps:
    - uses: actions/checkout@v3
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
   
    - name: aaa
      if: ${{ ! inputs.version }}
      run: echo "TAG"
    - name: aaa
      if: ${{ ! inputs.version }}
      run: echo "TAG"

    - name: github environment
      run: |
          git_hash=$(git rev-parse --short HEAD) 
          echo "GIT_SHORT_SHA=$git_hash" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: echo action used variables
      run: |
          echo '${{  toJSON(env) }}' 
          echo "::notice ::Git Short Sha: ${{env.GIT_SHORT_SHA}}"
          echo "::notice ::Git Branch: ${{env.GIT_BRANCH}}"
          echo "::notice ::Semantic release number: ${{ inputs.version }}"

    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Pump version number
      run: echo ${{ inputs.version }}
